#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J particle-gpu
#SBATCH -o auto-particle-gpu.stdout
#SBATCH -n 1         
#SBATCH -p gpu
#SBATCH -t 00:20:00     
rm gpusum.txt
ibrun ./gpu -n 10000 -s gpusum.txt
ibrun ./gpu -n 20000 -s gpusum.txt
ibrun ./gpu -n 40000 -s gpusum.txt
ibrun ./gpu -n 80000 -s gpusum.txt
ibrun ./gpu -n 160000 -s gpusum.txt
#ibrun ./serial -n 10000 -s gpusum.txt
#ibrun ./serial -n 20000 -s gpusum.txt
#ibrun ./serial -n 40000 -s gpusum.txt
#ibrun ./serial -n 80000 -s gpusum.txt
#ibrun ./serial -n 160000 -s gpusum.txt
#./autograder -v gpu -s gpusum.txt
